/obj/structure/ritualcircle/baotha/proc/baothaarmor(mob/living/carbon/human/target)
	if(!HAS_TRAIT(target, TRAIT_DEPRAVED))
		loc.visible_message(span_cult("THE RITE REJECTS ONE NOT OF HER LOVE"))
		return
	target.Stun(60)
	target.Knockdown(60)
	to_chat(target, span_userdanger("DELECTABLE PAIN!"))
	target.emote("Agony")
	playsound(loc, 'sound/combat/newstuck.ogg', 50)
	if(HAS_TRAIT(target, TRAIT_INFINITE_STAMINA) || (target.mob_biotypes & MOB_UNDEAD))
		loc.visible_message(span_cult("Great hooks come from the rune, embedding into [target]'s ankles, pulling them onto the rune. Then, into their wrists. As their black, rotten lux is torn from their chest, the very essence of their body surges to form it into armor. "))
		target.Paralyze(120)
	else
		loc.visible_message(span_cult("Great hooks come from the rune, embedding into [target]'s ankles, pulling them onto the rune. Then, into their wrists. Their lux is torn from their chest, and reforms into armor. "))
	spawn(20)
		playsound(loc, 'sound/combat/hits/onmetal/grille (2).ogg', 50)
		target.equipOutfit(/datum/outfit/job/roguetown/baothaarmor)
		target.apply_status_effect(/datum/status_effect/debuff/devitalised)
		if(!HAS_TRAIT(target, TRAIT_OVERTHERETIC))
			ADD_TRAIT(target, TRAIT_OVERTHERETIC, TRAIT_MIRACLE)
		spawn(40)
			to_chat(target, span_purple("All will love you and despair."))
