/datum/unit_test/ratworld_rarity/Run()
	if(get_ratworld_rarity_name(RW_RARITY_COMMON) != "Common")
		Fail("Rarity name for common is incorrect")
	if(get_ratworld_rarity_slot_count(RW_RARITY_EPIC) != 3)
		Fail("Attribute slot count for epic is incorrect")
	if(ratworld_format_rarity_examine(1) != "1 Common item")
		Fail("Singular formatting is incorrect")
	if(ratworld_format_rarity_examine(5) != "5 Common items")
		Fail("Plural formatting is incorrect")
