name: BYOND Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BYOND_MAJOR: 516
  BYOND_MINOR: 1673
  SPACEMAN_DMM_VERSION: suite-1.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Restore BYOND cache
        uses: actions/cache@v4
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-BYOND-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      
      - name: Install BYOND
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install -y make gcc unzip libcurl4:i386
          bash tools/ci/install_byond.sh

      - name: Compile BYOND project
        run: |
          ls -h $HOME/
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build.sh

      - name: Check for errors
        id: check-errors
        run: |
          if grep -q "error" *.log; then
            echo "::error ::Compilation failed with errors."
            exit 1
          else
            echo "Compilation succeeded without critical errors."
          fi

  run_linters:
    name: Run Linters
    needs: build
    uses: ./.github/workflows/run_linters.yml
